set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g base-index 1
setw -g pane-base-index 1

set -g escape-time 0

set-option -g mode-keys vi

set-window-option -g automatic-rename on
set-option -g set-titles on

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind S new-session

# copy and paste options
unbind Escape
bind [ copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer

set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# sesh command for navigating tmux sessions via fzf
bind-key "t" run-shell "~/.config/tmux/sesh.sh"

bind r source-file ~/.tmux.conf \; display "Reloaded!"

set-option -g default-shell /opt/homebrew/bin/fish

set-option -g status-left ""

bind g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit"

set -g status-style "bg=#f0f0f0,fg=#383a42"
set -g pane-border-style "fg=#d0d0d0"
set -g pane-active-border-style "fg=#4078f2"
set -g message-style "bg=#fafafa,fg=#383a42"

set -g status-right "[ #S ] "
set -g status-left-length 20

set -g window-status-format " ○"
set -g window-status-style "fg=#a0a1a7"
set -g window-status-current-format " ●"
set -g window-status-current-style "#{?window_zoomed_flag,fg=#c18401,fg=#4078f2}"

set -g window-status-bell-style "fg=#e45649,nobold"

run -b '~/.tmux/plugins/tpm/tpm'
